// AUTO-GENERATED by scripts/fetch-github-projects.mjs — do not edit by hand.
// Regenerated on every build (prebuild / pages:build).
import type { Project } from "./projects";

export const githubProjects: Project[] = [
  {
    "id": "prompt-playground",
    "title": "Prompt Playground",
    "description": "A web based platform to test, version, and auto-improve AI prompts, tools, and agent skills.",
    "longDescription": "A web based platform to test, version, and auto-improve AI prompts, tools, and agent skills.",
    "tags": [
      "TypeScript"
    ],
    "techStack": [
      "TypeScript"
    ],
    "gradient": "from-blue-500 to-blue-600",
    "icon": "monitor",
    "url": "/projects/prompt-playground",
    "github": "https://github.com/sebbyrule/prompt-playground",
    "status": "active",
    "stars": 0,
    "language": "TypeScript",
    "updatedAt": "2026-06-24T20:10:14Z"
  },
  {
    "id": "sa3-studio",
    "title": "Sa3 Studio",
    "description": "A combination of Stable Audio 3 and Demucs to create audio and separate the tracks in one place",
    "longDescription": "A combination of Stable Audio 3 and Demucs to create audio and separate the tracks in one place",
    "tags": [
      "Python"
    ],
    "techStack": [
      "Python"
    ],
    "gradient": "from-purple-500 to-purple-600",
    "icon": "zap",
    "url": "/projects/sa3-studio",
    "github": "https://github.com/sebbyrule/sa3-studio",
    "status": "active",
    "stars": 0,
    "language": "Python",
    "updatedAt": "2026-06-24T18:22:35Z"
  },
  {
    "id": "agentkernal",
    "title": "Agentkernal",
    "description": "a kernal based AI Agent",
    "longDescription": "a kernal based AI Agent",
    "tags": [
      "Python"
    ],
    "techStack": [
      "Python"
    ],
    "gradient": "from-orange-500 to-orange-600",
    "icon": "zap",
    "url": "/projects/agentkernal",
    "github": "https://github.com/sebbyrule/agentkernal",
    "status": "active",
    "stars": 0,
    "language": "Python",
    "updatedAt": "2026-06-21T02:12:09Z"
  },
  {
    "id": "questvault",
    "title": "Questvault",
    "description": "A gamified task tracker with LLM and MCP integration",
    "longDescription": "A gamified task tracker with LLM and MCP integration",
    "tags": [
      "TypeScript"
    ],
    "techStack": [
      "TypeScript"
    ],
    "gradient": "from-green-500 to-green-600",
    "icon": "monitor",
    "url": "/projects/questvault",
    "github": "https://github.com/sebbyrule/questvault",
    "status": "active",
    "stars": 0,
    "language": "TypeScript",
    "updatedAt": "2026-06-19T10:41:01Z"
  },
  {
    "id": "appropriated-kitchen",
    "title": "Appropriated Kitchen",
    "description": "My NextJS cooking blog",
    "longDescription": "My NextJS cooking blog",
    "tags": [
      "TypeScript"
    ],
    "techStack": [
      "TypeScript"
    ],
    "gradient": "from-pink-500 to-pink-600",
    "icon": "monitor",
    "url": "/projects/appropriated-kitchen",
    "github": "https://github.com/sebbyrule/AppropriatedKitchen",
    "status": "active",
    "stars": 0,
    "language": "TypeScript",
    "updatedAt": "2026-06-15T18:16:32Z"
  },
  {
    "id": "pi-wiki",
    "title": "Pi Wiki",
    "description": "A wiki library light enough to run on a Raspberry Pi",
    "longDescription": "A wiki library light enough to run on a Raspberry Pi",
    "tags": [
      "HTML"
    ],
    "techStack": [
      "HTML"
    ],
    "gradient": "from-cyan-500 to-cyan-600",
    "icon": "monitor",
    "url": "/projects/pi-wiki",
    "github": "https://github.com/sebbyrule/Pi-Wiki",
    "status": "active",
    "stars": 0,
    "language": "HTML",
    "updatedAt": "2026-06-15T15:17:13Z"
  }
];
